### ISSUE TITLE
hero-section

### ISSUE THREAD

**Issue by Labenas** [front-end-by-rimantas/17-grupe-portfolio-personal#9]
- generate html using JS
- align h,p and a elements in same vertical as Logo
- design button
- button color on left side and right side different
- button hover over shadow
- choose correct size of picture
- create responsive design

**Comment by belauzas** [comment]
In what order we should display text vs. image on mobile?
- text above + image below OR
- image above + text below
Any ideas? 🤔

**Comment by Labenas** [comment]
I would align text + button to center.
![image](https://user-images.githubusercontent.com/66065598/88664900-714abb80-d0e6-11ea-9b4e-0d103f999186.png)

**Comment by belauzas** [comment]
Looks great 👍
